from dataclasses import dataclass

@dataclass
class TelemetryReading:
    """
    Represents one telemetry reading generated by a simulated device.

    Python uses snake_case field names internally.
    The to_api_payload() method converts them into the camelCase
    field names expected by the FastAPI backend.
    """
    
    temperature: float       # Current storage temperature in degrees Celsius.
    humidity: float          # Current relative humidity percentage.
    battery_level: float    # Current battery charge percentage.
    generated_power: float  # Renewable power currently being generated in watts.
    cooling_load: float     # Current cooling system load in watts.
    wind_speed: float       # Current simulated wind speed in metres per second.
    status: str = "normal"  # Current operational status of the device.
    
    def to_api_payload(self, device_id: str) -> dict:
        """
        Convert this reading into the JSON payload required by POST /telemetry.
        """
        return {
            "deviceId": device_id,
            "temperature": self.temperature,
            "humidity": self.humidity,
            "batteryLevel": self.battery_level,
            "generatedPower": self.generated_power,
            "coolingLoad": self.cooling_load,
            "windSpeed": self.wind_speed,
            "status": self.status,
        }