"""add ai summaries table

Revision ID: 43de451d0200
Revises: 68fafdad1b24
Create Date: 2026-08-07 13:30:06.444859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43de451d0200'
down_revision: Union[str, Sequence[str], None] = '68fafdad1b24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=30), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('data_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('telemetry_count', sa.Integer(), nullable=False),
    sa.Column('active_alert_count', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_summaries_created_at'), 'ai_summaries', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_summaries_device_id'), 'ai_summaries', ['device_id'], unique=False)
    op.create_index(op.f('ix_ai_summaries_risk_level'), 'ai_summaries', ['risk_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_summaries_risk_level'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_device_id'), table_name='ai_summaries')
    op.drop_index(op.f('ix_ai_summaries_created_at'), table_name='ai_summaries')
    op.drop_table('ai_summaries')
    # ### end Alembic commands ###
