from datetime import datetime

from pydantic import BaseModel, ConfigDict, EmailStr, Field

class UserRegister(BaseModel):
    """
    Request body for registering a new user.
    This schema defines what data the frontend/client must send
    when creating a new account.
    """
    name: str = Field(..., min_length=2, max_length=100)        #User's full name
    email: EmailStr     # EmailStr validates that the input looks like a valid email address
    password: str = Field(..., min_length=8, max_length=128)     # Plain password sent during registration but will be hased before saving
    
class UserLogin(BaseModel):
    """
    Request body for user login.
    The user sends email and password.
    If they are valid, the backend returns a JWT access token.
    """
    email: EmailStr     # User's registered email address.
    password: str        # Plain password sent during login.
    
class Token(BaseModel):
    """
    Response body returned after successful login.
    The frontend will store this token and send it with protected requests.
    """
    access_token: str       # JWT access token generated by the backend.
    token_type: str = "bearer"         # Token type is usually "bearer" for JWT-based auth.
    
class UserResponse(BaseModel):
    """
    Safe user response returned to the frontend.
    """
    id: int         # User ID from the database.
    name: str       # User's full name.
    email: EmailStr     # User's email address.
    created_at: datetime        # Account creation timestamp.
    model_config = ConfigDict(from_attributes=True)       # Allows Pydantic to convert SQLAlchemy model objects into this response schema.